### PR TITLE
Fix === for multiple mocks of the same model

### LINKED ISSUE #60: Rails 7.1: mock_model is not always === the class it mocks
#54 reported, and #55 fixed an issue where Rails 7.1 has removed the `ActiveRecord::Base#===` method. We found that the issue is only fixed in _some_ cases, but not all. Specifically, when you have multiple mock_model’s in the same spec file, `#===` only gets implemented on the first instance.

```rb
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  gem "rails"
  gem "rspec-activemodel-mocks"
  gem "rspec"
  gem "sqlite3"
end

require "active_record"

ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Schema.define { create_table(:posts) }

Post = Class.new(ActiveRecord::Base)

require "rspec/autorun"

RSpec.describe "#===" do
  before do
    @foo = mock_model(Post)
    @bar = mock_model(Post)
    @baz = mock_model(Post)
  end

  it "works for the first mock_model" do
    expect(Post === @foo).to be(true)
  end

  it "works for the second mock_model" do
    expect(Post === @bar).to be(true)
  end

  it "works for the third mock_model" do
    expect(Post === @baz).to be(true)
  end
end
```

The output from running this file is

```
Failures:

  1) #=== works for the second mock_model
     Failure/Error: expect(Post === @bar).to be(true)
     
       expected true
            got false
     # repro.rb:35:in `block (2 levels) in <main>'

  2) #=== works for the third mock_model
     Failure/Error: expect(Post === @baz).to be(true)
     
       expected true
            got false
     # repro.rb:39:in `block (2 levels) in <main>'

Finished in 0.0144 seconds (files took 0.22345 seconds to load)
3 examples, 2 failures

Failed examples:

rspec repro.rb:34 # #=== works for the second mock_model
rspec repro.rb:38 # #=== works for the third mock_model
```

### PR DESCRIPTION
**Pull request by bquorning**
When the same model is mocked more than once in the same context, comparing with the model class using `#===` would only return true for the first of the mocks. All following mocks would return false when compared to the original model class using `#===`.

For `#===` to work correctly, we register each mock in a "mock_store" on the `RSpec::ActiveModel::Mocks::Mocks` module. The store is implemented as an RSpec stub, so it is reset after each spec example.

Fixes #60

I realize that I’m adding some complex code into some already-complex code, so please let me know if you’d rather have it implemented in some other way.

### CODE REVIEW

**Comment by JonRowe** [comment]
Can you rebase this please

File: lib/rspec/active_model/mocks/mocks.rb [hunk 1]
```diff
@@ -135,11 +135,16 @@ def self.param_delimiter; "-"; end
                 :blank? => false }.merge(stubs)
 
       double("#{model_class.name}_#{stubs[:id]}", stubs).tap do |m|
+        mock_store_klass = RSpec::ActiveModel::Mocks::Mocks
         if model_class.method(:===).owner == Module && !stubs.key?(:===)
+          allow(mock_store_klass).to receive(:mock_store) do
+            @mock_store ||= Hash.new { |h, k| h[k] = [] }
+          end
```
Comment (JonRowe) [inline lib/rspec/active_model/mocks/mocks.rb:142]:
```suggestion
          allow(model_class).to receive(:__rspec_mocks) do
            @mock_store ||= []
          end
```

File: lib/rspec/active_model/mocks/mocks.rb [hunk 2]
```diff
@@ -135,11 +135,16 @@ def self.param_delimiter; "-"; end
...
           allow(model_class).to receive(:===).and_wrap_original do |original, other|
-            m === other || original.call(other)
+            mock_store_klass.mock_store[model_class].any? { |ms| ms === other } || original.call(other)
```
Comment (JonRowe) [inline lib/rspec/active_model/mocks/mocks.rb:144]:
```suggestion
            model_class.__rspec_mocks.include(other) || original.call(other)
```

File: lib/rspec/active_model/mocks/mocks.rb [hunk 3]
```diff
@@ -135,11 +135,16 @@ def self.param_delimiter; "-"; end
...
           end
         end
+        mock_store_klass.mock_store[model_class] << m if mock_store_klass.respond_to?(:mock_store)
```
Comment (JonRowe) [inline lib/rspec/active_model/mocks/mocks.rb:147]:
```suggestion
        model_class.__rspec_mocks << m
```

File: lib/rspec/active_model/mocks/mocks.rb [hunk 4]
```diff
@@ -135,11 +135,16 @@ def self.param_delimiter; "-"; end
                 :blank? => false }.merge(stubs)
 
       double("#{model_class.name}_#{stubs[:id]}", stubs).tap do |m|
+        mock_store_klass = RSpec::ActiveModel::Mocks::Mocks
```
Comment (JonRowe) [inline lib/rspec/active_model/mocks/mocks.rb:138]:
```suggestion
```

**Review by JonRowe — CHANGES_REQUESTED** [review]
I see why you used a stub to store this data (so its automatically cleared), but rather than a global, I suggest stubing it on the model itself, its slightly neater

**Comment by bquorning** [comment]
I went back and forth on stubbing globally or on the model itself, but chose global because 1) we don’t accidentally override a method on the model itself, and 2) one spec fails on Rails 7.1 when I stub on the model itself.

However, I think you are correct, it _is_ better to stub on the model. I will look into why the spec is failing.

File: lib/rspec/active_model/mocks/mocks.rb (hunk 1 above)
Comment (bquorning) [reply lib/rspec/active_model/mocks/mocks.rb]: I think the `@mock_store` gets defined in the wrong context (RSpec ExampleGroup or Example), so it would need to change to e.g.
```rb
model_class.instance_variable_get(:@mock_store) ||
  model_class.instance_variable_set(:@mock_store, [])
```
But when I do that, I get specs failing with

> `#<Double "MockableModel_1037"> was originally created in one example but has leaked into another example and can no longer be used. rspec-mocks' doubles are designed to only last for one example, and you need to create a new one in each example you wish to use it for.`

Comment (JonRowe) [reply lib/rspec/active_model/mocks/mocks.rb]: That raises a good point, as the context this is executing is the example, we can actually just define a variable without a mock and it will be cleaned up, I've pushed an alternative implementation to this PR

Comment (bquorning) [reply lib/rspec/active_model/mocks/mocks.rb]: That is neat, thanks @JonRowe. Feel free to squash the commits as you see fit.

**Comment by JonRowe** [comment]
Released in 1.2.1, thanks!

**Comment by bquorning** [comment]
Thank you Jon 👍🏼
